ALTER TYPE "AssetType" RENAME VALUE 'BANK' TO 'BANK_ACCOUNT';

ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'VEHICLE';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'REAL_ESTATE';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'PRECIOUS_METAL';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'SECURITIES';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'BUSINESS';
ALTER TYPE "AssetType" ADD VALUE IF NOT EXISTS 'COLLECTIBLE';
